-- Monitoring reports — stores email reports generated by the worker every 30 minutes.
-- status: 'sent' | 'failed' | 'skipped'
-- skipped: email disabled (REPORT_EMAIL_ENABLED=false) or SMTP not configured
-- failed:  SMTP configured but delivery failed (network, auth, etc.)
-- sent:    successfully delivered

create table if not exists public.monitoring_reports (
  id            uuid        primary key default gen_random_uuid(),
  created_at    timestamptz not null default now(),
  period_start  timestamptz not null,
  period_end    timestamptz not null,
  recipient_email text,
  subject       text,
  body          text,
  status        text        not null check (status in ('sent', 'failed', 'skipped')),
  error_message text,
  metrics       jsonb
);

create index if not exists monitoring_reports_created_at_idx
  on public.monitoring_reports(created_at desc);
